#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

# Check ESLint Standards
echo '🏗️👷 Testing and checking your code before committing'
npm run check-lint ||
(
        echo '😤🏀👋😤 Get that weak stuff out of here! 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# If everything passes... Now we can commit
echo '✅ Code Check Passed'
